name: Pull Request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: api

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Make gradlew executable
        run: chmod +x ./gradlew

  linter:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: api

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Run Kotlin Linter
        run: ./gradlew detekt
      - name: Make gradlew executable
        run: chmod +x ./gradlew
